# TAKE $_POST VALUES FROM LANDING.PHP AND PUSH THEM TO "LOG" TABLE
# ...


# AUTHENTICATE / CREATE SESSION USING EMAIL AS KEY FOR SELECT QUERY -- SELECT * FROM USER WHERE email LIKE "$_POST['email']"
$email = $_POST['']
$first_name = 
$last_name = 